### ISSUE TITLE
problem install inetmanet-2.0

### ISSUE THREAD

**Issue by syantic** [aarizaq/inetmanet-3.x#1]
hi aarizaq,

i have problem install the inemanet. the problem was 

Simulation terminated with exit code: 1
Working directory: C:/omnetpp-4.2.2/aarizaq-inetmanet-2.0-f58a819/examples/wireless/throughput
Command line: c:/omnetpp-4.2.2/bin/opp_run.exe -r 0 -n ../..;../../../src -l ../../../src/inet omnetpp.ini

Environment variables:
OMNETPP_ROOT=c:/omnetpp-4.2.2
PATH=;C:/omnetpp-4.2.2/aarizaq-inetmanet-2.0-f58a819/src;c:\omnetpp-4.2.2\bin;c:\omnetpp-4.2.2\msys\bin;c:\omnetpp-4.2.2\mingw\bin;c:/omnetpp-4.2.2/ide/jre/bin/client;c:/omnetpp-4.2.2/ide/jre/bin;c:/omnetpp-4.2.2/ide/jre/lib/i386;.;C:\omnetpp-4.2.2\msys\local\bin;c:\omnetpp-4.2.2\mingw\bin;C:\omnetpp-4.2.2\msys\bin;c:\omnetpp-4.2.2\bin;c:\Program Files\Common Files\Microsoft Shared\Windows Live;c:\Windows\system32;c:\Windows;c:\Windows\System32\Wbem;c:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\EgisTec\MyWinLocker 3\x86;c:\Program Files (x86)\EgisTec\MyWinLocker 3\x64;c:\Program Files\WIDCOMM\Bluetooth Software\;c:\Program Files\WIDCOMM\Bluetooth Software\syswow64;c:\Program Files (x86)\Common Files\Softimage;c:\Program Files\Common Files\Softimage;c:\Program Files (x86)\QuickTime\QTSystem\;c:\omnetpp-4.2.2\ide;
OMNETPP_IMAGE_PATH=c:\omnetpp-4.2.2\images

can you please help me

**Comment by aarizaq** [comment]
can you run the example with the debug, with this information I don't know what is the error cause.

I have launched the example without problems

**Comment by ialonso** [comment]
Hello

I have installed inetmanet 2.0 but I have this problem, error en:
src->linklayer->ieee80211mesh->nodes->... "import inet.linklayer.IWirelessNicMulti;"

can you please help me?

**Comment by aarizaq** [comment]
I have removed the entries, it's safe to remove it

-----Mensaje original-----

**Comment by cleyb** [comment]
Hi,

I have posted this message also in omnet mail list (sorry for duplicating): 

I just installed INETMANET 2 (aarizaq-inetmanet-2.0) in
Omnet 4.2.2 Windows. After importing the project in one workspace and
building it, the file libinet.dll is generated in inetmanet-2.0\src
directory. Also, I have managed to run some of the examples included.

The problem is: everytime I open the project "inemanet-2.0" Omnet
reports a lot of NED Consistency Problem errors in some NED files
located in directory /inetmanet-2.0/src/nodes/ethernet.

These are the errors listed:

Description Resource    Path    Location    Type
'BComponent': no such module type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 34 NED Consistency Problem
'Cache1Q': no such module type  Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 49 NED Consistency Problem
'Cache1Q': no such module type  Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 45 NED Consistency Problem
'EthernetLink': no such module type EthernetHost.ned    /inetmanet-2.0/src/nodes/ethernet   line 25 NED Consistency Problem
'IComponent': no such module type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 46 NED Consistency Problem
'ITagTable': no such module type    BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 56 NED Consistency Problem
'MVRP': no such module type BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 78 NED Consistency Problem
'MVRP': no such module type Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 65 NED Consistency Problem
'MVRP': no such module type Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 61 NED Consistency Problem
'PortFilt': no such module type Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 37 NED Consistency Problem
'PortFilt1ad': no such module type  Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 41 NED Consistency Problem
'Relay1Q': no such module type  Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 32 NED Consistency Problem
'Relay1Q': no such module type  Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 28 NED Consistency Problem
'RSTP': no such module type BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 73 NED Consistency Problem
'RSTP': no such module type Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 60 NED Consistency Problem
'RSTP': no such module type Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 56 NED Consistency Problem
'TesterObject': no such module type Tester.ned  /inetmanet-2.0/src/nodes/ethernet   line 23 NED Consistency Problem
cannot assign parameters of a submodule of unknown type BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 37 NED Consistency Problem
cannot assign parameters of a submodule of unknown type BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 38 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 40 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 41 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 42 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 43 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 50 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 51 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 52 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 53 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 76 NED Consistency Problem
cannot configure gates of a submodule of unknown type   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 81 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 36 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 37 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 38 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 39 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 45 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 46 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 63 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 68 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 32 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 33 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 34 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 35 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 41 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 42 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 59 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 64 NED Consistency Problem
cannot configure gates of a submodule of unknown type   EthernetHost.ned    /inetmanet-2.0/src/nodes/ethernet   line 29 NED Consistency Problem
cannot configure gates of a submodule of unknown type   EthernetHost.ned    /inetmanet-2.0/src/nodes/ethernet   line 30 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Tester.ned  /inetmanet-2.0/src/nodes/ethernet   line 27 NED Consistency Problem
cannot configure gates of a submodule of unknown type   Tester.ned  /inetmanet-2.0/src/nodes/ethernet   line 28 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ethernet.EthernetLink'   EthernetHost.ned    /inetmanet-2.0/src/nodes/ethernet   line 5  NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021AD.PortFilt1ad'  Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 12 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021AH.BComponent'   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 12 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021AH.IComponent'   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 10 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021AH.ITagTable'    BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 11 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021AH.PortFilt1ah'  BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 13 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021Q.Cache1Q'   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 14 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021Q.Cache1Q'   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 11 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021Q.PortFilt'  Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 9  NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021Q.Relay1Q'   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 13 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.ieee8021Q.Relay1Q'   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 10 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.MVRP.MVRP'   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 16 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.MVRP.MVRP'   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 17 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.MVRP.MVRP'   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 14 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.RSTP.RSTP'   BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 15 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.RSTP.RSTP'   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 16 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.RSTP.RSTP'   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 13 NED Consistency Problem
imported NED type not found: 'inet.linklayer.ieee8021d.Tester.TesterObject' Tester.ned  /inetmanet-2.0/src/nodes/ethernet   line 8  NED Consistency Problem
wrong destination gate: submodule 'bcomponent' has no gate named 'BportsIn' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 91 NED Consistency Problem
wrong destination gate: submodule 'bcomponent' has no gate named 'BportsIn' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 132    NED Consistency Problem
wrong destination gate: submodule 'bcomponent' has no gate named 'MVRPPort' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 136    NED Consistency Problem
wrong destination gate: submodule 'bcomponent' has no gate named 'RSTPPort' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 135    NED Consistency Problem
wrong destination gate: submodule 'icomponent' has no gate named 'CGatesIn' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 96 NED Consistency Problem
wrong destination gate: submodule 'icomponent' has no gate named 'CGatesIn' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 100    NED Consistency Problem
wrong destination gate: submodule 'icomponent' has no gate named 'CGatesIn' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 104    NED Consistency Problem
wrong destination gate: submodule 'icomponent' has no gate named 'CGatesIn' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 108    NED Consistency Problem
wrong destination gate: submodule 'icomponent' has no gate named 'CGatesIn' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 112    NED Consistency Problem
wrong destination gate: submodule 'icomponent' has no gate named 'CGatesIn' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 116    NED Consistency Problem
wrong destination gate: submodule 'icomponent' has no gate named 'IGatesIn' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 90 NED Consistency Problem
wrong destination gate: submodule 'linklayer' has no gate named 'lowerLayerIn'  EthernetHost.ned    /inetmanet-2.0/src/nodes/ethernet   line 38 NED Consistency Problem
wrong destination gate: submodule 'linklayer' has no gate named 'upperLayerIn'  EthernetHost.ned    /inetmanet-2.0/src/nodes/ethernet   line 43 NED Consistency Problem
wrong destination gate: submodule 'PortFilt' has no gate named 'GatesIn'    Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 75 NED Consistency Problem
wrong destination gate: submodule 'PortFilt' has no gate named 'GatesIn'    Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 77 NED Consistency Problem
wrong destination gate: submodule 'PortFilt' has no gate named 'GatesIn'    Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 71 NED Consistency Problem
wrong destination gate: submodule 'PortFilt' has no gate named 'GatesIn'    Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 73 NED Consistency Problem
wrong destination gate: submodule 'relay' has no gate named 'GatesIn'   Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 76 NED Consistency Problem
wrong destination gate: submodule 'relay' has no gate named 'GatesIn'   Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 72 NED Consistency Problem
wrong destination gate: submodule 'relay' has no gate named 'MVRPGate'  Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 81 NED Consistency Problem
wrong destination gate: submodule 'relay' has no gate named 'MVRPGate'  Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 77 NED Consistency Problem
wrong destination gate: submodule 'relay' has no gate named 'RSTPGate'  Ether1ADBridge.ned  /inetmanet-2.0/src/nodes/ethernet   line 80 NED Consistency Problem
wrong destination gate: submodule 'relay' has no gate named 'RSTPGate'  Ether1QBridge.ned   /inetmanet-2.0/src/nodes/ethernet   line 76 NED Consistency Problem
wrong destination gate: submodule 'testerObject' has no gate named 'In' Tester.ned  /inetmanet-2.0/src/nodes/ethernet   line 39 NED Consistency Problem
wrong source gate: submodule 'bcomponent' has no gate named 'BportsOut' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 90 NED Consistency Problem
wrong source gate: submodule 'bcomponent' has no gate named 'BportsOut' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 131    NED Consistency Problem
wrong source gate: submodule 'icomponent' has no gate named 'CGatesOut' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 95 NED Consistency Problem
wrong source gate: submodule 'icomponent' has no gate named 'CGatesOut' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 99 NED Consistency Problem
wrong source gate: submodule 'icomponent' has no gate named 'CGatesOut' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 103    NED Consistency Problem
wrong source gate: submodule 'icomponent' has no gate named 'CGatesOut' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 107    NED Consistency Problem
wrong source gate: submodule 'icomponent' has no gate named 'CGatesOut' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 111    NED Consistency Problem
wrong source gate: submodule 'icomponent' has no gate named 'CGatesOut' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 115    NED Consistency Problem
wrong source gate: submodule 'icomponent' has no gate named 'IGatesOut' BEB.ned /inetmanet-2.0/src/nodes/ethernet   line 91 NED Consistency Problem

Can you please help? 
Thanks a lot in advance.

**Comment by aarizaq** [comment]
you need to include the 802.1q in the project, you can do with the properties->omnet->features
