### ISSUE TITLE
Wrong setting of COLLISION or BITERROR in linklayer/radio/Radio.cc

### ISSUE THREAD

**Issue by pvd6** [aarizaq/inetmanet-3.x#12]
Hi all,
I am concerned about how packets are marked as collision or error in Radio.cc.

In Radio.cc l. 687, if radioModel->isReceivedCorrectly(airframe, list) is false and 
the SNRList has size > 1, the packet it is marked as COLLISION:
 airframe->getEncapsulatedPacket()->setKind(list.size()>1 ? COLLISION : BITERROR);

However, that is not always true. I have checked that sometimes I get bit errors, but they are marked as collisions.
Is there any particular reason for this implementation or should it be corrected?

Since snirMin is just computed a few lines earlier, it can be used to mark packets as collisions.

Thanks a lot

Best regards

**Comment by aarizaq** [comment]
Not at all, Radio.cc doesn’t have the necessary information to determine if it is a collision or bit error because it doesn’t have access to the variable snirThreshol, without this value it is impossible to determine if it is a collision or bit error

De: pvd6 [mailto:notifications@github.com] 
Enviado el: lunes, 15 de julio de 2013 16:57
Para: aarizaq/inetmanet-2.0
Asunto: [inetmanet-2.0] Wrong setting of COLLISION or BITERROR in linklayer/radio/Radio.cc (#12)

Hi all,
I am concerned about how packets are marked as collision or error in Radio.cc.

In Radio.cc l. 687, if radioModel->isReceivedCorrectly(airframe, list) is false and 
the SNRList has size > 1, the packet it is marked as COLLISION:
airframe->getEncapsulatedPacket()->setKind(list.size()>1 ? COLLISION : BITERROR);

However, that is not always true. I have checked that sometimes I get bit errors, but they are marked as collisions.
Is there any particular reason for this implementation or should it be corrected?

Since snirMin is just computed a few lines earlier, it can be used to mark packets as collisions.

Thanks a lot

Best regards

**Comment by pvd6** [comment]
Yes, I am aware of that. Then, maybe radioModel should mark the packet in isReceivedCorrectly(airframe, list). Otherwise,  packets which are rejected because of biterrors, are incorrectly marked as COLLISION

**Comment by aarizaq** [comment]
I have uploaded a modification that solve the problem

Date: Mon, 15 Jul 2013 09:16:26 -0700

**Comment by pvd6** [comment]
Ok. Thanks a lot.
