### ISSUE TITLE
Severe problems in building inetmanet 2.0

### ISSUE THREAD

**Issue by snash4** [aarizaq/inetmanet-3.x#18]
Hi... 
  I have been trying to build manet 2.0 but no success so far...
I used lot of hit and trial method like changing project preferences, deleting error reporting examples .. but still no success...
I m using Omnet++, i cloned the inetmanet and imported it into omnetpp and then tried build all... it z giving me errors like these...

‘frequency’ was not declared in this scope  ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 158    C/C++ Problem

‘uint32_t’ does not name a type ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 90 C/C++ Problem

‘uint32_t’ does not name a type ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 87 C/C++ Problem

‘bandwidth’ was not declared in this scope  ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 88 C/C++ Problem

‘frequency’ was not declared in this scope  ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 91 C/C++ Problem

‘class ModulationType’ has no member named ‘getDataRate’    WifiMode.cc /inetmanet-2.0/src/linklayer/ieee80211/mac  line 1207   C/C++ Problem

‘dataRate’ was not declared in this scope   ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 154    C/C++ Problem

‘constellationSize’ was not declared in this scope  ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 156    C/C++ Problem
‘class ModulationType’ has no member named ‘getFrequency’   WifiMode.cc /inetmanet-2.0/src/linklayer/ieee80211/mac  line 1348   C/C++ Problem

‘dataRate’ was not declared in this scope   ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 106    C/C++ Problem

‘class ModulationType’ has no member named ‘getFrequency’   WifiMode.cc /inetmanet-2.0/src/linklayer/ieee80211/mac  line 1394   C/C++ Problem

‘dataRate’ was not declared in this scope   ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 128    C/C++ Problem

‘constellationSize’ was not declared in this scope  ModulationType.h    /inetmanet-2.0/src/linklayer/radio  line 138    C/C++ Problem

PLEASE HELP ME OUT...
THANKS

**Comment by aarizaq** [comment]
Ok, I suspect that the problem is the not inclusion of the stdint.h header, I have just uploaded a path that solve the problem

De: Sheikh Nasrullah [mailto:notifications@github.com] 
Enviado el: viernes, 21 de febrero de 2014 20:13
Para: aarizaq/inetmanet-2.0
Asunto: [inetmanet-2.0] Severe problems in building inetmanet 2.0 (#18)

Hi... 
I have been trying to build manet 2.0 but no success so far...
I used lot of hit and trial method like changing project preferences, deleting error reporting examples .. but still no success...
I m using Omnet++, i cloned the inetmanet and imported it into omnetpp and then tried build all... it z giving me errors like these...

‘frequency’ was not declared in this scope ModulationType.h /inetmanet-2.0/src/linklayer/radio line 158 C/C++ Problem

‘uint32_t’ does not name a type ModulationType.h /inetmanet-2.0/src/linklayer/radio line 90 C/C++ Problem

‘uint32_t’ does not name a type ModulationType.h /inetmanet-2.0/src/linklayer/radio line 87 C/C++ Problem

‘bandwidth’ was not declared in this scope ModulationType.h /inetmanet-2.0/src/linklayer/radio line 88 C/C++ Problem

‘frequency’ was not declared in this scope ModulationType.h /inetmanet-2.0/src/linklayer/radio line 91 C/C++ Problem

‘class ModulationType’ has no member named ‘getDataRate’ WifiMode.cc /inetmanet-2.0/src/linklayer/ieee80211/mac line 1207 C/C++ Problem

‘dataRate’ was not declared in this scope ModulationType.h /inetmanet-2.0/src/linklayer/radio line 154 C/C++ Problem

‘constellationSize’ was not declared in this scope ModulationType.h /inetmanet-2.0/src/linklayer/radio line 156 C/C++ Problem
‘class ModulationType’ has no member named ‘getFrequency’ WifiMode.cc /inetmanet-2.0/src/linklayer/ieee80211/mac line 1348 C/C++ Problem

‘dataRate’ was not declared in this scope ModulationType.h /inetmanet-2.0/src/linklayer/radio line 106 C/C++ Problem

‘class ModulationType’ has no member named ‘getFrequency’ WifiMode.cc /inetmanet-2.0/src/linklayer/ieee80211/mac line 1394 C/C++ Problem

‘dataRate’ was not declared in this scope ModulationType.h /inetmanet-2.0/src/linklayer/radio line 128 C/C++ Problem

‘constellationSize’ was not declared in this scope ModulationType.h /inetmanet-2.0/src/linklayer/radio line 138 C/C++ Problem

PLEASE HELP ME OUT...
THANKS

**Comment by michaelkirsche** [comment]
Dear Alfonso,

I've tested the last revision with your patch and everything works fine under Linux now.

Thanks a lot,
Michael
