### ISSUE TITLE
Ieee80211Descriptor::data[] is not correctly ordered

### ISSUE THREAD

**Issue by pvd6** [aarizaq/inetmanet-3.x#22]
Hi, 
when I try to set up a Ieee80211Nic with opMode="p" and bitrate=6Mbps, it says "mode not valid" in a pop-up in Tk.
I have checked this mode exists in the array Ieee80211Descriptor::data[] , but when calling Ieee80211Descriptor::findIdx( ) it does not find it with the std::lower_bound search.

The problem is that, for lower_bound to work properly, Ieee80211Descriptor::data[] must be ordered previously. However, the 'p' values appear before the 'n' values.
When I change the order it works. 
Am I rigth or is there a reason why 'p' values should appear before?

Thanks a lot,

**Comment by aarizaq** [comment]
Ups it is true, the proble is in the funtion
ieee80211DescriptorCompareModeBitrate

they compare the mode to determine the order
a.mode < b.mode
and the problem is that 'n' < 'p', if you use lineal search you don't have problem but if you use std::lower_bound the imputs must be ordered lower values before
