### ISSUE TITLE
Using and distributing other linkcache metrics?

### ISSUE THREAD

**Issue by FcoAlvarez** [aarizaq/inetmanet-3.x#23]
I'm using a metric other than hop count, each node calculate its own, but could not pass the cost to other nodes using linkcache. i tried piggybacking in the costvector of the sending rreq packet, but cause more trouble in other parts of code.
Any place on the code where i can put the cost to distribute to other nodes?
hope you could help. thanks.

**Comment by aarizaq** [comment]
It is possible to include a “cheat”, you can include a “shared” memory between nodes, but the inconvenience of this method is that it doesn’t show the incomplete acknowledge due to the propagation delay because all nodes have immediate acknowledge of any change in the shared data base

De: FcoAlvarez [mailto:notifications@github.com] 
Enviado el: miércoles, 24 de diciembre de 2014 20:40
Para: aarizaq/inetmanet-2.0
Asunto: [inetmanet-2.0] Using and distributing other linkcache metrics? (#23)

I'm using a metric other than hop count, each node calculate its own, but could not pass the cost to other nodes using linkcache. i tried piggybacking in the costvector of the sending rreq packet, but cause more trouble in other parts of code.
Any place on the code where i can put the cost to distribute to other nodes?
hope you could help. thanks.
