### ISSUE TITLE
inetmanet 3 build error on omnet++ 5.0

### ISSUE THREAD

**Issue by hajji7777** [aarizaq/inetmanet-3.x#29]
Hi Aarizaq.
I followed those steps to intall inetmanet on omnet++ 5.0 : 
1. Extract the zip file to my workspace(samples);
2. Import the inetmanet folder as "Existing projects into workspace";
3. Build the project.
I had an error in "INETDefs.h" file (/inetmanet-3.x-inetmanet-3.0/src/inet/common/INETDefs.h), precisely in the #include "inet/**opp_defines**.h" line : "inet/opp_defines.h **not** found"
![inetdefs](https://cloud.githubusercontent.com/assets/22495486/18910433/d7ec091e-856f-11e6-8f8d-4e6a381b199e.png)
The file "opp_defines.h" does not exist in both inetmanet and inet tree.
Please help me to resolve this issue (i need to work with last inetmanet version).
Best regards.
Hajji

**Comment by aarizaq** [comment]
This file should be created automatically for omnet.

De: hajji7777 [mailto:notifications@github.com]
Enviado el: miércoles, 28 de septiembre de 2016 12:28
Para: aarizaq/inetmanet-3.x inetmanet-3.x@noreply.github.com
Asunto: [aarizaq/inetmanet-3.x] inetmanet 3 build error on omnet++ 5.0 (#29)

Hi Aarizaq.
I followed those steps to intall inetmanet on omnet++ 5.0 :
1. Extract the zip file to my workspace(samples);
2. Import the inetmanet folder as "Existing projects into workspace";
3. Build the project.
I had an error in "INETDefs.h" file (/inetmanet-3.x-inetmanet-3.0/src/inet/common/INETDefs.h), precisely in the #include "inet/opp_defines.h" line : "inet/opp_defines.h not found"
[inetdefs]https://cloud.githubusercontent.com/assets/22495486/18909945/ac97f1e4-856d-11e6-93d7-b7056f6b6f60.png
The file "opp_defines.h" does not exist in both inetmanet and inet tree.
Please help me to resolve this issue (i need to work with last inetmanet version).
Best regards.
Hajji

**Comment by aarizaq** [comment]
The problem is fixed

De: hajji7777 [mailto:notifications@github.com]
Enviado el: miércoles, 28 de septiembre de 2016 12:28
Para: aarizaq/inetmanet-3.x inetmanet-3.x@noreply.github.com
Asunto: [aarizaq/inetmanet-3.x] inetmanet 3 build error on omnet++ 5.0 (#29)

Hi Aarizaq.
I followed those steps to intall inetmanet on omnet++ 5.0 :
1. Extract the zip file to my workspace(samples);
2. Import the inetmanet folder as "Existing projects into workspace";
3. Build the project.
I had an error in "INETDefs.h" file (/inetmanet-3.x-inetmanet-3.0/src/inet/common/INETDefs.h), precisely in the #include "inet/opp_defines.h" line : "inet/opp_defines.h not found"
https://cloud.githubusercontent.com/assets/22495486/18909945/ac97f1e4-856d-11e6-93d7-b7056f6b6f60.png
The file "opp_defines.h" does not exist in both inetmanet and inet tree.
Please help me to resolve this issue (i need to work with last inetmanet version).
Best regards.
Hajji
