### ISSUE TITLE
inetmanet 3.5 build errors on omnetpp 5.1

### ISSUE THREAD

**Issue by hajji7777** [aarizaq/inetmanet-3.x#32]
Dear Aarizaq.
I want to work with the last inetmanet 3.5, based on inet 3.5, compatible with the last omnetpp 5.1.
When i build the inetmanet project, i get a lot of errors "C/C++ Problem" messages:
![inetmanet build errors](https://cloud.githubusercontent.com/assets/22495486/26028355/ad3c7578-3816-11e7-93f4-570aee20fd34.png)
The problem was noted when omnetpp try to creat the shared library "libINET.dll"
How to solve this issue?

**Comment by aarizaq** [comment]
With this information I don’t know, I don’t see any error message.


De: hajji7777 [mailto:notifications@github.com]
Enviado el: sábado, 13 de mayo de 2017 21:04
Para: aarizaq/inetmanet-3.x <inetmanet-3.x@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [aarizaq/inetmanet-3.x] inetmanet 3.5 build errors on omnetpp 5.1 (#32)


Dear Aarizaq.
I want to work with the last inetmanet 3.5, based on inet 3.5, compatible with the last omnetpp 5.1.
When i build the inetmanet project, i get a lot of errors "C/C++ Problem" messages:
[inetmanet build errors]<https://cloud.githubusercontent.com/assets/22495486/26028355/ad3c7578-3816-11e7-93f4-570aee20fd34.png>
The problem was noted when omnetpp try to creat the shared library "libINET.dll"
How to solve this issue?

**Comment by hajji7777** [comment]
New version downloaded. Still had the same problems!
The older(April 2017) version works fine!

**Comment by aarizaq** [comment]
Have your read the install file and have you done this?
$git submodule update --init

**Comment by aarizaq** [comment]
You need to download the submodules
$git submodule update --init

De: hajji7777 [mailto:notifications@github.com]
Enviado el: miércoles, 17 de mayo de 2017 1:07
Para: aarizaq/inetmanet-3.x <inetmanet-3.x@noreply.github.com>
CC: Alfonso <aarizaq_m@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [aarizaq/inetmanet-3.x] inetmanet 3.5 build errors on omnetpp 5.1 (#32)


New version downloaded. Still had the same problems!
The older(April 2017) version works fine!

**Comment by hajji7777** [comment]
How to(steps) download the submodules?
I never download the submodules for inetmanet(just import and build it)!

**Comment by hajji7777** [comment]
Problem solved!

**Comment by hanhanbinbin** [comment]
dear @hajji7777 & @aarizaq , how u solve the problem?where to download the submodule??Can you show me the steps because i m facing the same problem

**Comment by aarizaq** [comment]
$git submodule update --init

**Comment by hanhanbinbin** [comment]
dear @aarizaq, which directory should i type in this command?? 
/c/Users/USER/Desktop/inetmanet-3.x-inetmanet-3.5$git submodule update --init?
Do i need to download inet-3.5.0 and import to my omnet workspace separately ??or need to merge it with inet-3.x-inetmanet-3.5x? and how it can be done??sorry for asking these type of question because i m new to omnet++

**Comment by hanhanbinbin** [comment]
![problem](https://user-images.githubusercontent.com/30208187/28275262-f22c3a76-6b45-11e7-9f6a-8ab823105df6.png)
i have no right to access it to clone and it told not a git repository

**Comment by aarizaq** [comment]
you are trying to clone the repository with the authorization of the owner
Check the git documentation, this is the instrution to clone the repository withou the authorizations
git clone git://github.com/inet-framework/inet.git

**Comment by hajji7777** [comment]
Dear hanhanbinbin,
To solve the issue, i just download the sub directories: "showchases" and "tutorials" then add them to the main directory(inetmanet).
Regards.
